title: Shihan Kanungo
author: Shihan Kanungo
url: https://www.shihankanungo.github.io/shihanmoonwalk/ # root address of the site
description: > # description of the site (multiple lines allowed) 
  <img src="images/pic.jpg" alt="Avatar" style="width:250px; border-radius:50%;"> <br />
  Hello there! I’m Shihan&mdash;thanks for stopping by. I live in Palo Alto, CA. I am deeply fascinated by mathematics, physics, language, and music. I play the violin, compose with my MPK Mini Plus, and have a music taste that defies genre (and occasionally logic). When I’m not actively immersed in one of these pursuits, there’s a good chance I’m sitting very still, appearing contemplative&mdash;while secretly daydreaming about my next snack. I aspire to nurture my passions and use them to make meaningful contributions to the world ... ideally with a bit of joy, curiosity, and the occasional pastry along the way.
          <br /><br />

          <small><b>Recent news</b>: <i>Ramanujan's Pi links to black holes.</i> Researchers at the Centre for High Energy Physics (CHEP), Indian Institute of Science (IISc) discovered that Ramanujan’s classic &#960;-formulas arise naturally in modern theories describing critical phenomena and black holes. The connection suggests his early mathematics may have foreshadowed key structures in today’s high-energy physics.</small>
          <br /><br />
          <small><b>Currently reading</b>: <i>The Shadow Rising</i> by Robert Jordan and <i>Crime and Punishment</i> by Fyodor Dostoevsky.</small>
          <br /><br />
          <small><b>Recent Movies</b>: <i>Mickey and the Bear</i> (2019 d. Annabelle Attanasio), <i>Almost Famous</i> (2000 d. Cameron Crowe), and <i>Mad Max: Fury Road</i> (2015 d. George Miller)</small>
          <br /><br />
          <small><b>Current Music Recs</b>: <i>Renaissance</i> by Beyonce (<a href="https://open.spotify.com/album/6FJxoadUE4JNVwWHghBwnb?si=RSfqXehORo2QK4Dg95FFuA">Spotify</a>), and <i>Remain In Light</i> by Angelique Kidjo. Also, these playlists, with one song each from my favorite albums from 2024: <a href="https://open.spotify.com/playlist/0plT5tvEl6lVLrQDk0X3eu?si=fe06480b57f64999">pop</a> and <a href="https://open.spotify.com/playlist/5iHDUPHT30iNd4Feg0yg4f?si=737a0b1a27924789">jazz</a>. </small>
          <br /><br /><br /><br />
          
  <img className="mt-8 md:mt-12 w-1/2 sm:w-1/3 lg:w-1/4" src="/signature.png" alt="signature of shihan" aria-hidden="true" />    
permalink: /:slug

favicon: "./logo.png" # relative path to site's favicon



#theme: moonwalk # if you are using GitHub Pages, change it to remote_theme: abhinavs/moonwalk
remote_theme: abhinavs/moonwalk

theme_config:
  appearance: "dark" # can be "light", "dark" or "auto"
  appearance_toggle: true # if appearance can be switched by user
  back_home_text: "Home" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description
  show_navbar: true # show horizontal navbar
  show_footer: true # show footer links in home page,add in _data/home.yml
  show_math: true # show links in math page,add in _data/home.yml
  show_activities: true # show links in activities page,add in _data/home.yml
  show_personal: true # show links in about page,add in _data/home.yml
  show_mop: true # show links in mop page,add in _data/home.yml
  show_courses: true # show links in course page,add in _data/home.yml
  show_copyright: true # show copyright notice in footer
  # following keys are using to create home layout
  show_projects: true # show projects as cards, add in _data/home.yml
  show_blog: false # show blog posts added in _posts
  show_old_projects: false # show old projects as cards, add in _data/home.yml
  show_misc_list: false # show generic vertical list for misc details, add _data/home.yml
  show_reading_time: true # show number of words and reading time in the blog posts
  show_tags: true # show tags in a blog posts
  # options for "home" page
  home:
    title_projects: 
    title_misc_list: Details
    title_blog: Blog
    # title_old_projects: Old Projects

soopr:
  publish_token: "" # sign up at https://www.soopr.co to get your publish token and personalize share and reaction options

highlighter: rouge

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-soopr-seo-tag
